heat_template_version: 2014-10-16
description: 'Extra Pre-Deployment Config, multiple'

parameters:
  server:
    type: string

resources:

  # Note depends_on may be used for serialization if ordering is important
  RHELRegistration:
    type: /usr/share/openstack-tripleo-heat-templates/extraconfig/pre_deploy/rhel-registration/rhel-registration.yaml
    properties:
        server: {get_param: server}

outputs:  
  deploy_stdout:  
    value:  
      list_join:  
      - ''  
      - - {get_attr: [RHELRegistration, deploy_stdout]}
